version: '3.7'

volumes:
  postgres:

services:

  postgres:
    container_name: postgres
    image: postgres:15.3
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'

  proxy:
    container_name: proxy
    image: joram87/psql_anonymizing_proxy
    volumes:
      - ./config_examples/config.yaml:/config.yaml
    ports:
      - "8080:8080"
