version: '3.7'

volumes:
  postgres:

services:

  postgres:
    image: postgres:15.3
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
#    command: postgres -c log_min_messages=INFO -c log_statement=all
