port: 8080
server_uri: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
columns:
  - name: email
    function: email

  - name: password
    function: password.stars

  - name: first_name
    function: name.first

  - name: middle_name
    function: name.middle

  - name: last_name
    function: name.last
